starting_probabilities:
  Storm: 0.07142857142857142
  LightRain: 0.07142857142857142
  MediumCloud: 0.07142857142857142
  HeavyFog: 0.07142857142857142
  Clear: 0.07142857142857142
  LightCloud: 0.07142857142857142
  Random: 0.0
  Hazy: 0.07142857142857142
  HeavyCloud: 0.07142857142857142
  Rain: 0.07142857142857142
  Foggy: 0.07142857142857142
  HeavyFogWithRain: 0.07142857142857142
  FogWithRain: 0.07142857142857142
  Thunderstorm: 0.07142857142857142
  Overcast: 0.07142857142857142
